version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=test
      - TZ=America/New_York
    volumes:
      - $PWD/portfolio_data:/config
    restart: unless-stopped
    #debug
    ports:
      - 3333:3306
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    user: "1000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - mariadb
  collector:
    # image: jrcichra/grafana-portfolio
    build: .
    volumes:
      - $PWD/portfolio.yml:/app/portfolio.yml
    depends_on:
      - mariadb
